default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Taxi4343") %>
  socket: /tmp/mysql.sock

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: buero_dev
    socket: /tmp/mysql.sock

production:
  primary:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_general_ci
    database: buero_production
    username: "buero"
    password: "Taxi4343;"
    socket: /var/run/mysqld/mysqld.sock
  cache:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_general_ci
    database: buero_production_cache
    username: "buero"
    password: "Taxi4343;"
    socket: /var/run/mysqld/mysqld.sock
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate