default: &default
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :username) || 'root' %>
  password: <%= Rails.application.credentials.dig(:database, :password) || '' %>
  socket: /tmp/mysql.sock

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    adapter: mysql2
    database: buero_dienstleistungen_development
    socket: /tmp/mysql.sock

production:
  primary:
    adapter: mysql2
    database: buero_production
    username: <%= Rails.application.credentials.dig(:database, :username) || 'root' %>
    password: <%= Rails.application.credentials.dig(:database, :password) || '' %>
    socket: /var/run/mysqld/mysqld.sock
  cache:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_general_ci
    database: buero_production_cache
    username: <%= Rails.application.credentials.dig(:database, :username) || 'root' %>
    password: <%= Rails.application.credentials.dig(:database, :password) || '' %>
    socket: /var/run/mysqld/mysqld.sock
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate